analytics: {}
color:
  brandColors:
    - '#B8B8C0'
    - '#000000'
    - '#788080'
    - '#000000'
    - '#000000'
  brandStrength: 0.695945
  lightness: 0.759009
  rhythmicContrast: 0.572072
  saturation: 0.677927
cta: {}
layout_spectrum: 0.916666
name: King Law
opengraph: {}
purpose: []
typography_spectrum: 0.639639
