name: King Law
favicon: null
layout_spectrum: 0.00423
typography_spectrum: 0.92379
title: King Law PLLC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B8C0'
    - '#000000'
    - '#788080'
    - '#000000'
    - '#000000'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
