analytics: {}
color:
  brandColors:
    - '#B8B8C0'
    - '#000000'
    - '#788080'
    - '#000000'
    - '#000000'
  brandStrength: 0.695945
  lightness: 0.774774
  rhythmicContrast: 0.572072
  saturation: 0.710585
cta: {}
layout_spectrum: 0.230855
name: King Law
opengraph: {}
purpose: []
typography_spectrum: 1
