name: King Law
favicon: null
layout_spectrum: 0.00423
typography_spectrum: 0.92379
title: King Law PLLC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffcf0'
    - '#210d06'
    - '#27343c'
    - '#d9794f'
    - '#ecb568'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
